import {
  amber,
  blue,
  blueGrey,
  brown,
  cyan,
  deepOrange,
  deepPurple,
  green,
  grey,
  indigo,
  lightBlue,
  lightGreen,
  lime,
  orange,
  pink,
  purple,
  red,
  teal,
  yellow,
} from '@material-ui/core/colors';
import { IColors } from './IThemeConfig';

export const Colors: IColors[] = [
  { name: 'Amber', value: amber },
  { name: 'blue', value: blue },
  { name: 'blueGrey', value: blueGrey },
  { name: 'brown', value: brown },
  { name: 'cyan', value: cyan },
  { name: 'deepOrange', value: deepOrange },
  { name: 'deepPurple', value: deepPurple },
  { name: 'green', value: green },
  { name: 'grey', value: grey },
  { name: 'indigo', value: indigo },
  { name: 'lightBlue', value: lightBlue },
  { name: 'lightGreen', value: lightGreen },
  { name: 'lime', value: lime },
  { name: 'orange', value: orange },
  { name: 'pink', value: pink },
  { name: 'purple', value: purple },
  { name: 'red', value: red },
  { name: 'teal', value: teal },
  { name: 'yellow', value: yellow },
];
